server:
  port: '9091'

logging:
  level:
    root: DEBUG
    com:
      schoool:
        management: DEBUG

kafka:
  consumer:
    bootstrap-servers: 'http://127.0.0.1:9092'
    group-id: 'school-service'